apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ygkpftxv6-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:568dfbacef9fe9ffd16d9735902822acc1a9142a@sha256:41a1b1111d6d3e216ef1ee9a034fde2f9658b973f25758cb9ab63440053a101c
          name: container-image
